os:
  - linux
language: node_js
node_js:
  - "node"
  - "14"
  - "12"
  - "10"

script:
  - npm test

after_success:
  - npm install coveralls
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
